.\"	$Id: unworkable.1,v 1.7 2009-01-29 05:59:40 niallo Exp $
.\"
.\" Copyright (c) 2007 Niall O'Higgins <niallo@unworkable.org>
.\" All rights reserved.
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd $Mdocdate: October 4 2008 $
.Dt UNWORKABLE 1
.Os
.Sh NAME
.Nm unworkable
.Nd download files via BitTorrent
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl s
.Op Fl g Ar port
.Op Fl p Ar port
.Op Fl t Ar tracefile
.Ar torrent
.Ek
.Sh DESCRIPTION
The
.Nm
program is used to download files via the BitTorrent protocol.
.Pp
When
.Nm
is executed with a valid .torrent file as an argument, it will proceed
to announce to the tracker, connect to peers and download the data.
Upon completion of the download, the program will exit, unless seed-mode
is enabled.
.Bl -tag -width Ds
.It Fl g Ar port
If specified, run the GUI control server on port
.Ar port .
By default, no GUI control server will run.
.It Fl p Ar port
If specified, listen for incoming BitTorrent peer connections on
.Ar port .
By default,
.Nm
does not accept incoming connections.
.It Fl s
Enable seed-mode, that is, keep running and seed after download is complete.
.It Fl t Ar tracefile
Trace execution, outputting to
.Ar tracefile .
.El
.Sh AUTHORS
The
.Nm
program was written by
.An Niall O'Higgins.
